GET http://localhost:8000/api/rapat?page=1&size=10


###
POST http://localhost:8000/api/rapat/9c4c8f31-7958-4f31-acb7-d83ae6b0dd9e/peserta
Content-Type: application/json

{
    "peserta": [
        {
            "nama": "John Doe",
            "keterangan": "Manager",
            "perwakilan": "Sales",
            "jenis": "Internal"
        },
        {
            "nama": "Jane Smith",
            "keterangan": "Analyst",
            "perwakilan": "Marketing",
            "jenis": "External"
        }
    ],
}


###
POST http://localhost:8000/api/rapat
Content-Type: application/json

{
    "nama":"Rapat Biasa",
    "urgensi":"Biasa"
}



###
POST http://localhost:8000/api/rapat/2
Content-Type: application/json

{
    "nama":"Rapat 3",
    "urgensi":"Luar Biasa",
    "lokasi":"Rumah Tetangga",
    "pemapar":"Bos",
    "_method":"PATCH"
}

###
POST http://localhost:8000/api/rapat/2/penanggung_jawab
Content-Type: application/multipart/form-data

{
    "nama_personil":"Sumoni Ahun, S.H",
    "role":"Tamu Undangan",
}

###

GET http://localhost:8000/api/rapat/2

###
POST http://localhost:8000/api/rapat/2/arahan_pimpinan
Content-Type: multipart/form-data

{
    "arahan":"Turunkan Anggaran DXX",
    "deadline":"Tamu Undangan ",
}


###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email":"admindsp@bssn.go.id",
    "password":"123456"
}


###
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name":"Rohmat XYZ",
    "unit_kerja":"DIT OPSAN (D23)",
    "email":"rohmat@bssn.go.id",
    "password":"123456",
    "role": "staff"
}


###
GET http://localhost:8000/api/tes
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzI5NTg3MjExLCJleHAiOjE3Mjk1OTA4MTEsIm5iZiI6MTcyOTU4NzIxMSwianRpIjoiOUE0c1VaUWpwTnMwUjVXOCIsInN1YiI6IjUiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiZW1haWwiOiJhaG1hZEBic3NuLmdvLmlkIiwibmFtZSI6IkFobWFkIFhYWFgiLCJyb2xlIjpbInN0YWZmIl0sIjAiOiJ1bml0X2tlcmphIn0.EEO4Vyp0WUJ-vKiH9qLNSY7Oz-tvsw7q9JTjfuMwNP0
